v0.1.0：使用SSC编译

diff --git a/bin/indeux b/bin/indeux
--- a/bin/indeux
+++ b/bin/indeux
@@ -1,8 +1,132 @@
 #!/bin/bash
 
-set -e
+## compiler: ssc-0.0.1-b4
+## host: Darwin YupyeSortaco.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 21:27:51 PDT 2024; root:xnu-11215.1.10~5/RELEASE_ARM64_T8112 arm64 arm Darwin
+## date: 20240831T172140Z
 
-source /opt/indeux/functions
+#!/bin/bash
+
+## include >>>
+Indeux_CheckPermission () 
+{ 
+    if [ "$(whoami)" != "root" ]; then
+        echo "indeux must be runned as root.";
+        exit 1;
+    fi
+}
+Indeux_Init () 
+{ 
+    echo "* Copying necessary files...";
+    mkdir -p ./.indeux/;
+    cp /opt/indeux/indeux.conf.example ./.indeux/indeux.conf;
+    echo "* Directory inited for indeux."
+}
+Indeux_InterateForDirectories () 
+{ 
+    echo "$1"/;
+    for i in $(ls "$1");
+    do
+        if [[ -d $1"/"$i ]]; then
+            Indeux_InterateForDirectories "$1""/""$i";
+        fi;
+    done
+}
+Indeux_PrintBrand () 
+{ 
+    echo "_______________________________________________________________";
+    echo "|                            indeux                             |";
+    echo "|            <github.com/Tarikko-ScetayhChan/indeux>            |";
+    echo "|                                                               |";
+    echo "|              Copyright 2024 Tarikko-ScetayhChan               |";
+    echo "|                  <weychon_lyon@outlook.com>                   |";
+    echo "|                <blog.tarikko-scetayhchan.top>                 |";
+    echo "|===============================================================|";
+    echo "|                                                               |";
+    echo "| This program is free software: you can redistribute it and/or |";
+    echo "| modify it under the terms of the GNU General Public License   |";
+    echo "| as published by the Free Software Foundation, either version  |";
+    echo "| 3 of the License, or (at your option) any later version.      |";
+    echo "|                                                               |";
+    echo "| This program is distributed in the hope that it will be       |";
+    echo "| useful, but WITHOUT ANY WARRANTY; without even the implied    |";
+    echo "| warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR       |";
+    echo "| PURPOSE. See the GNU General Public License for more details. |";
+    echo "| You should have received a copy of the GNU General Public     |";
+    echo "| License along with this program. If not, see                  |";
+    echo "| <https://www.gnu.org/licenses/>.                              |";
+    echo "|                                                               |";
+    echo "|_______________________________________________________________|"
+}
+Indeux_PrintUsage () 
+{ 
+    echo "Usage: indeux [ init | remove | version | gen ]"
+}
+Indeux_RemoveIndex () 
+{ 
+    echo -e "* Removing index:";
+    find . -name 'index.html' -type f -print -exec rm -rf {} \;;
+    echo
+}
+Slibs_PrintMessage () 
+{ 
+    echo -n "$1: ";
+    [[ "$2" = d* ]] && echo -en "\e[1m\e[037mdebug: \e[0m";
+    [[ "$2" = i* ]] && echo -en "\e[1m\e[092minfo: \e[0m";
+    [[ "$2" = w* ]] && echo -en "\e[1m\e[093mwarning: \e[0m";
+    [[ "$2" = e* ]] && echo -en "\e[1m\e[091merror: \e[0m";
+    [[ "$2" = f* ]] && echo -en "\e[1m\e[031mfafal: \e[0m";
+    echo "$3"
+}
+Slibs_PrintMessage_Debug () 
+{ 
+    Slibs_PrintMessage "$1" d "$2"
+}
+Slibs_PrintMessage_Error () 
+{ 
+    Slibs_PrintMessage "$1" e "$2"
+}
+Slibs_PrintMessage_Fafal () 
+{ 
+    Slibs_PrintMessage "$1" f "$2"
+}
+Slibs_PrintMessage_Fafal_InvalidExtensionName () 
+{ 
+    Slibs_PrintMessage_Fafal "$1" "Invalid extension name in \`$2'."
+}
+Slibs_PrintMessage_Fafal_ItemExists () 
+{ 
+    Slibs_PrintMessage_Fafal "$1" "\`$2' exists."
+}
+Slibs_PrintMessage_Fafal_ItemNotFound () 
+{ 
+    Slibs_PrintMessage_Fafal "$1" "\`$2' not found."
+}
+Slibs_PrintMessage_Fafal_SourceExpected () 
+{ 
+    Slibs_PrintMessage_Fafal "$1" "Source expected."
+}
+Slibs_PrintMessage_Fafal_TargetExpected () 
+{ 
+    Slibs_PrintMessage_Fafal "$1" "Target expected."
+}
+Slibs_PrintMessage_Fafal_TooManyArguments () 
+{ 
+    Slibs_PrintMessage_Fafal "$1" "To many arguments."
+}
+Slibs_PrintMessage_Info () 
+{ 
+    Slibs_PrintMessage "$1" i "$2"
+}
+Slibs_PrintMessage_Warning () 
+{ 
+    Slibs_PrintMessage "$1" w "$2"
+}
+Ssc_WriteCompilationInformation () 
+{ 
+    echo "$ssc_compilationInfo" >> "$ssc_target"
+}
+## <<<
+
 
 Indeux_CheckPermission
 
@@ -11,7 +135,7 @@ if [ "$1" = "init" ]; then
         Indeux_Init
         exit 0
     else
-        echo "* This directory is already inited for indeux. If necessary, operate \`sudo rm -rf ./.indeux/'."
+        Slibs_PrintMessage_Fafal "$0" "This directory is already inited for indeux. If necessary, operate \`sudo rm -rf ./.indeux/'."
         exit 1
     fi
 elif [ "$1" = "version" ]; then
@@ -22,7 +146,7 @@ elif [ "$1" = "remove" ]; then
     exit 0
 elif [ "$1" = "gen" ]; then
     if [ ! -f "./.indeux/indeux.conf" ]; then
-        echo "./.indeux/indeux.conf not found. Have you inited this directory for indeux?"
+        Slibs_PrintMessage_Fafal "$0" "./.indeux/indeux.conf not found. Have you inited this directory for indeux?"
         exit 1
     fi
 
